# Generated by Django 3.2.4 on 2021-07-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='项目名')),
                ('desc', models.CharField(max_length=200, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '项目',
                'db_table': 'project',
            },
        ),
    ]
