# Generated by Django 3.2.4 on 2021-07-28 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='变量名称')),
                ('base_url', models.CharField(max_length=200, verbose_name='base url')),
                ('headers', models.JSONField(blank=True, default=dict, null=True, verbose_name='公共头')),
                ('variables', models.JSONField(blank=True, default=dict, null=True, verbose_name='公共参数')),
            ],
            options={
                'verbose_name': '环境变量',
                'db_table': 'env',
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='描述'),
        ),
        migrations.CreateModel(
            name='ProjectEnv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.RESTRICT, related_name='env_param', to='manager.envparam', verbose_name='关联环境变量')),
                ('project', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.RESTRICT, related_name='project_env', to='manager.project', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': '项目对应环境',
                'db_table': 'project_env',
            },
        ),
    ]
