# Generated by Django 3.2.4 on 2021-07-27 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=250, verbose_name='变量名称')),
                ('key', models.CharField(max_length=50, verbose_name='key')),
                ('value', models.CharField(max_length=250, verbose_name='value')),
            ],
            options={
                'verbose_name': '环境变量',
                'db_table': 'env_param',
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='描述'),
        ),
        migrations.CreateModel(
            name='ProjectEnv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.RESTRICT, related_name='env_param', to='manager.envparam', verbose_name='关联环境变量')),
                ('project', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.RESTRICT, related_name='project_env', to='manager.project', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': '项目对应环境',
                'db_table': 'project_env',
            },
        ),
    ]
