# Generated by Django 3.2.4 on 2021-07-29 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20210728_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envparam',
            name='headers',
            field=models.JSONField(default=dict, null=True, verbose_name='公共头'),
        ),
        migrations.AlterField(
            model_name='envparam',
            name='variables',
            field=models.JSONField(default=dict, null=True, verbose_name='公共参数'),
        ),
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.CharField(blank=True, max_length=50, null=True, verbose_name='创建人')),
                ('name', models.CharField(max_length=250, verbose_name='api名称')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS')], max_length=20, verbose_name='请求方式')),
                ('url', models.CharField(max_length=250, verbose_name='URL路径')),
                ('headers', models.JSONField(default=dict, null=True, verbose_name='请求头')),
                ('body', models.JSONField(default=dict, null=True, verbose_name='请求参数')),
                ('project', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='project_api', to='manager.project', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': 'Api',
                'db_table': 'api',
            },
        ),
    ]
