# Generated by Django 3.2.4 on 2021-08-03 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20210729_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=250, verbose_name='测试用例名称')),
                ('variables', models.JSONField(null=True, verbose_name='variables')),
                ('parameters', models.JSONField(null=True, verbose_name='parameters')),
                ('export', models.JSONField(null=True, verbose_name='export')),
                ('project', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='project_case', to='manager.project', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': '测试用例',
                'db_table': 'test_case',
            },
        ),
        migrations.AlterField(
            model_name='api',
            name='method',
            field=models.CharField(choices=[('get', 'GET'), ('post', 'POST'), ('put', 'PUT'), ('delete', 'DELETE'), ('patch', 'PATCH'), ('head', 'HEAD'), ('options', 'OPTIONS')], max_length=20, verbose_name='请求方式'),
        ),
        migrations.CreateModel(
            name='TestStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='接口名称')),
                ('variables', models.JSONField(null=True, verbose_name='variables')),
                ('request', models.JSONField(default=dict, null=True, verbose_name='请求参数')),
                ('extract', models.JSONField(null=True, verbose_name='提取数据')),
                ('validate', models.JSONField(default=list, null=True, verbose_name='断言校验')),
                ('export', models.JSONField(null=True, verbose_name='export')),
                ('sort', models.IntegerField(default=0, null=True, verbose_name='排序')),
                ('case', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='case_step', to='manager.testcase', verbose_name='测试用例')),
                ('testcase', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_case', to='manager.testcase', verbose_name='用例引用')),
            ],
            options={
                'verbose_name': '测试步骤',
                'db_table': 'test_step',
                'ordering': ['sort', 'id'],
            },
        ),
    ]
