# Generated by Django 3.2.4 on 2021-08-10 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20210803_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=40, verbose_name='计划名称')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('author', models.CharField(max_length=50, verbose_name='创建人')),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_plan', to='manager.project', verbose_name='项目id')),
            ],
            options={
                'verbose_name': '测试计划',
                'db_table': 'plan',
            },
        ),
        migrations.CreateModel(
            name='PlanCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.RESTRICT, to='manager.testcase', verbose_name='测试用例')),
                ('plan', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.RESTRICT, related_name='plan_case', to='manager.plan', verbose_name='关联计划')),
            ],
            options={
                'verbose_name': '用例对应计划',
                'db_table': 'plan_case',
            },
        ),
    ]
