# Generated by Django 3.2.4 on 2021-08-11 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_plan_plancase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plancase',
            name='case',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.RESTRICT, related_name='case_testcase', to='manager.testcase', verbose_name='测试用例'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='Report')),
                ('path', models.CharField(blank=True, max_length=100, null=True, verbose_name='报告路径')),
                ('case', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_report', to='manager.testcase', verbose_name='关联用例')),
                ('plan', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_report', to='manager.plan', verbose_name='关联计划')),
            ],
            options={
                'verbose_name': '报告',
                'db_table': 'report',
            },
        ),
    ]
