# Generated by Django 3.2.4 on 2021-09-08 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_plan_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plancase',
            name='plan',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='plan_case', to='manager.plan', verbose_name='关联计划'),
        ),
        migrations.AlterField(
            model_name='projectenv',
            name='env',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='env_param', to='manager.envparam', verbose_name='关联环境变量'),
        ),
        migrations.AlterField(
            model_name='projectenv',
            name='project',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='project_env', to='manager.project', verbose_name='关联项目'),
        ),
        migrations.CreateModel(
            name='APICate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='分类名称')),
                ('desc', models.CharField(max_length=500, null=True, verbose_name='备注')),
                ('project', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cate_project', to='manager.project', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': 'APICate',
                'db_table': 'api_cate',
            },
        ),
        migrations.AddField(
            model_name='api',
            name='cate',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_cate', to='manager.apicate', verbose_name='分类'),
        ),
    ]
