# Generated by Django 3.2.4 on 2021-10-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_auto_20210908_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='author',
            field=models.CharField(max_length=50, null=True, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='api',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS')], max_length=20, verbose_name='请求方式'),
        ),
    ]
