# Generated by Django 3.2.4 on 2021-10-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_auto_20211015_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-create_time'], 'verbose_name': '报告'},
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='export',
        ),
        migrations.RemoveField(
            model_name='teststep',
            name='export',
        ),
        migrations.AddField(
            model_name='testcase',
            name='output',
            field=models.JSONField(null=True, verbose_name='output'),
        ),
        migrations.AddField(
            model_name='teststep',
            name='output',
            field=models.JSONField(null=True, verbose_name='output'),
        ),
    ]
